# MANTIS-EVOLUTION: Agent schema contracts
"""
Pydantic v2 models defining shared contracts between all agents
in the MANTIS AI multi-agent trading system.

These schemas are the single source of truth for inter-agent communication.
Every agent must produce and consume these models — no raw dicts allowed
across agent boundaries.
"""

from __future__ import annotations

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Literal

from pydantic import BaseModel, Field

# ---------------------------------------------------------------------------
# Roles
# ---------------------------------------------------------------------------


class AgentRole(str, Enum):
    """Enumeration of all agent roles in the multi-agent system."""

    TECHNICAL = "TECHNICAL"
    SENTIMENT = "SENTIMENT"
    RISK = "RISK"
    TRADER = "TRADER"
    FUND_MANAGER = "FUND_MANAGER"
    VISION = "VISION"
    RL_ADAPTIVE = "RL_ADAPTIVE"
    DRL_ENSEMBLE = "DRL_ENSEMBLE"


# ---------------------------------------------------------------------------
# Shared context
# ---------------------------------------------------------------------------


class MarketContext(BaseModel):
    """Shared market context passed to all agents at the start of each cycle."""

    epic: str
    timeframe: str = "15min"
    current_price: float
    atr: float
    features: dict[str, Any] = Field(default_factory=dict)
    regime: str | None = None
    sil_data: dict[str, Any] | None = None
    open_positions: int = 0
    equity: float = 0.0
    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    # Sprint 4: Vision AI + RAG context (optional, populated when enabled)
    vision_data: dict[str, Any] | None = None
    rag_context: str | None = None
    # Sprint 5: DRL ensemble signal (optional, populated when drl_enabled)
    drl_signal: dict[str, Any] | None = None


# ---------------------------------------------------------------------------
# Agent reports
# ---------------------------------------------------------------------------


class TechnicalReport(BaseModel):
    """Output produced by the TechnicalAgent after analysing price action."""

    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    symbol: str
    trend_direction: Literal["BULLISH", "BEARISH", "NEUTRAL"]
    strength_score: float = Field(ge=0.0, le=1.0)
    key_support_levels: list[float]
    key_resistance_levels: list[float]
    active_patterns: list[str]
    timeframe_consensus: dict[str, str]
    rationale: str


class SentimentReport(BaseModel):
    """Output produced by the SentimentAgent from news, social, and macro data."""

    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    composite_score: float = Field(ge=-1.0, le=1.0)
    fear_greed_index: float
    social_sentiment: float
    news_sentiment: float
    confidence: float = Field(ge=0.0, le=1.0)
    dominant_narrative: str


class RiskReport(BaseModel):
    """Output produced by the RiskAgent assessing current market and portfolio risk."""

    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    risk_score: float = Field(ge=0.0, le=1.0)
    volatility_regime: Literal["LOW", "MEDIUM", "HIGH", "EXTREME"]
    max_position_size_pct: float = Field(ge=0.0)
    recommended_stop_loss_pct: float = Field(ge=0.0)
    liquidity_score: float = Field(ge=0.0, le=1.0)
    blocking: bool = False
    rationale: str


# ---------------------------------------------------------------------------
# Trade proposal & debate
# ---------------------------------------------------------------------------


class TradeProposal(BaseModel):
    """A trade proposal generated by the TraderAgent, pending fund-manager approval."""

    timestamp: datetime = Field(default_factory=lambda: datetime.now(timezone.utc))
    action: Literal["BUY", "SELL", "HOLD"]
    confidence: float = Field(ge=0.0, le=1.0)
    size_pct: float = Field(ge=0.0)
    entry_price: float
    take_profit_levels: list[float]
    stop_loss: float
    rationale: str
    source_reports: dict[str, Any]


class DebateArgument(BaseModel):
    """A single argument contributed by an agent during the bull/bear debate."""

    side: Literal["BULL", "BEAR"]
    argument: str
    confidence: float = Field(ge=0.0, le=1.0)
    evidence: list[str]


class DebateSummary(BaseModel):
    """Aggregated outcome of the multi-agent bull/bear debate."""

    bull_arguments: list[DebateArgument]
    bear_arguments: list[DebateArgument]
    consensus: Literal["BULLISH", "BEARISH", "NEUTRAL"]
    consensus_confidence: float = Field(ge=0.0, le=1.0)
    key_disagreements: list[str]


# ---------------------------------------------------------------------------
# Final decision
# ---------------------------------------------------------------------------


class FinalDecision(TradeProposal):
    """
    The fund manager's final decision, extending TradeProposal with approval
    status, optional override reason, and a full agent audit trail.
    """

    approved: bool = False
    override_reason: str | None = None
    debate_summary: str | None = None
    agent_audit_trail: list[dict[str, Any]]
