"""
Strategy manager orchestrator.
Coordinates regime adaptation, signal generation, and portfolio allocation.
"""

from pathlib import Path

from loguru import logger

from src.models.schemas import PredictionResult
from src.strategy.portfolio_allocator import PortfolioAllocator
from src.strategy.regime_adapter import RegimeAdapter
from src.strategy.schemas import StrategyConfig, TradingSignal
from src.strategy.signal_generator import SignalGenerator

# Default location for per-asset thresholds produced by batch_oos_scorecard.py
_DEFAULT_THRESHOLDS_PATH = (
    Path(__file__).resolve().parent.parent.parent / "data" / "config" / "optimal_thresholds.json"
)


class StrategyManager:
    """
    Orchestrates the strategy pipeline:
    prediction -> regime adaptation -> signal generation.
    """

    def __init__(
        self,
        configs: dict[str, StrategyConfig] | None = None,
        excluded_epics: set[str] | None = None,
        scalp_mode: bool = False,
        orb_fvg_epics: set[str] | None = None,
    ):
        """
        Initialize strategy manager.

        Args:
            configs: Per-asset strategy configs. Uses defaults if None.
            excluded_epics: Epics to skip (decision=EXCLUDE from scorecard).
            scalp_mode: If True, use ScalpScoreStrategy as primary signal source.
            orb_fvg_epics: Epics to use ORB+FVG strategy (default: {"US500"}).
        """
        self._configs = configs or {}
        self.excluded_epics: set[str] = excluded_epics or set()
        self.scalp_mode = scalp_mode
        self._scalp_strategy = None
        self._orb_fvg_strategy = None
        self.orb_fvg_epics: set[str] = orb_fvg_epics if orb_fvg_epics is not None else {"US500"}
        if scalp_mode:
            from src.strategy.scalp_score_strategy import ScalpScoreStrategy
            self._scalp_strategy = ScalpScoreStrategy()
        if self.orb_fvg_epics:
            from src.strategy.orb_fvg_strategy import OrbFvgStrategy
            self._orb_fvg_strategy = OrbFvgStrategy()

    @classmethod
    def from_optimal_thresholds(
        cls,
        path: Path | None = None,
    ) -> "StrategyManager":
        """
        Create StrategyManager with per-asset confidence thresholds
        from the optimal_thresholds.json generated by batch_oos_scorecard.py.

        If the file doesn't exist, falls back to default config.
        """
        from src.backtest.scorecard import load_optimal_thresholds

        thresholds_path = path or _DEFAULT_THRESHOLDS_PATH
        data = load_optimal_thresholds(thresholds_path)

        if data is None:
            logger.info("No optimal_thresholds.json found, using default configs")
            return cls()

        per_asset = data.get("per_asset", {})
        default_conf = data.get("default_confidence", 0.40)
        configs: dict[str, StrategyConfig] = {}
        excluded: set[str] = set()

        for epic, info in per_asset.items():
            decision = info.get("decision", "KEEP")
            if decision == "EXCLUDE":
                excluded.add(epic)
                continue
            min_conf = info.get("min_confidence", default_conf)
            configs[epic] = StrategyConfig(epic=epic, min_confidence=min_conf)

        logger.info(
            f"Loaded optimal thresholds for {len(configs)} assets "
            f"({len(excluded)} excluded) from {thresholds_path}"
        )
        return cls(configs=configs, excluded_epics=excluded)

    def _get_config(self, epic: str) -> StrategyConfig:
        """Get or create config for an asset."""
        if epic not in self._configs:
            self._configs[epic] = StrategyConfig(epic=epic)
        return self._configs[epic]

    def process_prediction(
        self,
        prediction: PredictionResult,
        epic: str,
        market_data: dict,
    ) -> TradingSignal:
        """
        Process an ML prediction into a trading signal.

        Args:
            prediction: ML model prediction
            epic: Asset epic code
            market_data: Dict with keys:
                - current_price (float, required)
                - atr (float, required)
                - rsi (float, optional)
                - regime (str, optional)

        Returns:
            TradingSignal with direction and suggested levels
        """
        current_price = market_data.get("current_price")
        atr = market_data.get("atr")
        if current_price is None or atr is None:
            raise ValueError(
                "market_data must contain 'current_price' and 'atr' keys"
            )
        if not (isinstance(current_price, (int, float)) and current_price > 0):
            raise ValueError(f"Invalid current_price: {current_price}")
        if not (isinstance(atr, (int, float)) and atr > 0):
            raise ValueError(f"Invalid ATR: {atr}")

        # Route to ORB+FVG for configured epics during NYSE hours
        if (
            self._orb_fvg_strategy is not None
            and epic in self.orb_fvg_epics
            and market_data.get("m1_bars") is not None
        ):
            return self._process_orb_fvg(epic, market_data)

        if self.scalp_mode and self._scalp_strategy is not None:
            return self._process_scalp(prediction, epic, market_data)

        rsi = market_data.get("rsi")
        regime = market_data.get("regime")
        adx = market_data.get("adx")

        # Get base config and adapt for regime
        base_config = self._get_config(epic)
        adapted_config = RegimeAdapter.adapt_params(regime, base_config)

        # Generate signal
        signal = SignalGenerator.generate_signal(
            prediction=prediction,
            epic=epic,
            current_price=current_price,
            atr=atr,
            rsi=rsi,
            regime=regime,
            config=adapted_config,
            adx=adx,
        )

        # Set strategy name (SignalGenerator doesn't set it)
        if signal.strategy_name is None:
            signal.strategy_name = "ml_strategy"

        logger.info(
            f"Strategy [{epic}]: {signal.direction.value} "
            f"conf={signal.confidence:.2f} regime={regime}"
        )

        return signal

    def _process_orb_fvg(
        self,
        epic: str,
        market_data: dict,
    ) -> TradingSignal:
        """Route to ORB+FVG strategy using M1 bars from market_data."""
        import polars as pl

        m1_bars = market_data["m1_bars"]
        current_price = float(market_data["current_price"])
        atr = float(market_data["atr"])

        config = StrategyConfig(
            epic=epic,
            stop_multiplier=1.0,
            risk_reward_ratio=2.0,
        )

        current_bar = {"close": current_price, "atr_14": atr}

        signal = self._orb_fvg_strategy.generate_signal(
            epic, current_bar, m1_bars, config
        )

        if signal.direction.value != "HOLD":
            logger.info(
                f"ORB+FVG [{epic}]: {signal.direction.value} "
                f"conf={signal.confidence:.2f}"
            )

        return signal

    def _process_scalp(
        self,
        prediction: PredictionResult,
        epic: str,
        market_data: dict,
    ) -> TradingSignal:
        """Scalp mode: technical score first, ML as boost layer."""
        import polars as pl
        from datetime import datetime, timezone
        from src.strategy.schemas import SignalDirection
        from src.models.schemas import SignalClass

        current_price = float(market_data["current_price"])
        atr = float(market_data["atr"])
        utc_hour = datetime.now(timezone.utc).hour

        config = StrategyConfig(
            epic=epic,
            stop_multiplier=1.0,
            risk_reward_ratio=2.0,
            min_confidence=0.40,
        )

        # Build current_bar from market_data
        current_bar = {
            "close": current_price,
            "atr_14": atr,
            "rsi_14": market_data.get("rsi", 50),
            "adx_14": market_data.get("adx", 0),
            "ema_9": market_data.get("ema_9", 0),
            "ema_21": market_data.get("ema_21", 0),
            "macd_histogram": market_data.get("macd_histogram", 0),
            "macd": market_data.get("macd", 0),
            "macd_signal": market_data.get("macd_signal", 0),
            "volume": market_data.get("volume", 0),
            "volume_sma_20": market_data.get("volume_sma_20", 0),
            "bb_upper": market_data.get("bb_upper", 0),
            "bb_lower": market_data.get("bb_lower", 0),
            "bb_middle": market_data.get("bb_middle", 0),
            "keltner_upper": market_data.get("keltner_upper", 0),
            "keltner_lower": market_data.get("keltner_lower", 0),
            "vwap": market_data.get("vwap", 0),
            "utc_hour": utc_hour,
            "htf_bias": market_data.get("htf_bias"),
        }

        recent_bars = market_data.get("recent_bars", pl.DataFrame({"close": [current_price]}))

        # Step 1: Technical score signal
        signal = self._scalp_strategy.generate_signal(epic, current_bar, recent_bars, config)

        if signal.direction == SignalDirection.HOLD:
            logger.info(f"Scalp [{epic}]: HOLD (score too low)")
            return signal

        # Step 2: ML boost layer
        ml_direction = {
            SignalClass.BUY: SignalDirection.BUY,
            SignalClass.SELL: SignalDirection.SELL,
            SignalClass.HOLD: SignalDirection.HOLD,
        }.get(prediction.signal_class, SignalDirection.HOLD)

        pre_ml_confidence = signal.confidence

        if ml_direction == signal.direction and prediction.confidence > 0.40:
            # ML agrees -> full confidence (no change)
            agreement = "agree"
            logger.info(
                f"Scalp [{epic}]: {signal.direction.value} "
                f"(score->signal, ML agrees conf={prediction.confidence:.2f})"
            )
        elif ml_direction == SignalDirection.HOLD or prediction.confidence <= 0.40:
            # ML neutral -> mild reduction (×0.75), not halving.
            # Halving a 3/7 (0.43) signal to 0.21 kills it below the 0.25 floor.
            # Neutral ML means "no opinion", not "bad signal".
            agreement = "neutral"
            signal = signal.model_copy(update={"confidence": signal.confidence * 0.75})
            logger.info(
                f"Scalp [{epic}]: {signal.direction.value} "
                f"(score->signal, ML neutral -> 0.75x conf={signal.confidence:.2f})"
            )
        else:
            # ML disagrees — halve confidence but never veto
            # GURU: technical confluence is the decision maker, ML only adjusts sizing
            agreement = "disagree"
            signal = signal.model_copy(update={"confidence": signal.confidence * 0.5})
            logger.info(
                f"Scalp [{epic}]: {signal.direction.value} "
                f"(ML disagrees {ml_direction.value} conf={prediction.confidence:.2f} -> half conf={signal.confidence:.2f})"
            )

        # Add ML audit data to signal metadata
        ml_audit = {
            "signal_class": prediction.signal_class,
            "signal_name": prediction.signal_name,
            "confidence": round(prediction.confidence, 4),
            "probabilities": prediction.probabilities,
            "agreement": agreement,
            "confidence_before": round(pre_ml_confidence, 4),
            "confidence_after": round(signal.confidence, 4),
        }
        updated_metadata = {**signal.metadata, "ml": ml_audit}
        signal = signal.model_copy(update={"strategy_name": "scalp_score", "metadata": updated_metadata})
        return signal

    def get_allocation(self, regime: str | None = None) -> dict[str, float]:
        """
        Get portfolio allocation weights.

        Args:
            regime: Market regime for adjustment

        Returns:
            Dict of epic -> allocation weight
        """
        return PortfolioAllocator.get_allocation(regime)
