"""
Strategy manager orchestrator.
Coordinates regime adaptation, signal generation, and portfolio allocation.
"""

from pathlib import Path

from loguru import logger

from src.models.schemas import PredictionResult
from src.strategy.portfolio_allocator import PortfolioAllocator
from src.strategy.regime_adapter import RegimeAdapter
from src.strategy.schemas import StrategyConfig, TradingSignal
from src.strategy.signal_generator import SignalGenerator

# Default location for per-asset thresholds produced by batch_oos_scorecard.py
_DEFAULT_THRESHOLDS_PATH = (
    Path(__file__).resolve().parent.parent.parent / "data" / "config" / "optimal_thresholds.json"
)


class StrategyManager:
    """
    Orchestrates the strategy pipeline:
    prediction -> regime adaptation -> signal generation.
    """

    def __init__(
        self,
        configs: dict[str, StrategyConfig] | None = None,
        excluded_epics: set[str] | None = None,
    ):
        """
        Initialize strategy manager.

        Args:
            configs: Per-asset strategy configs. Uses defaults if None.
            excluded_epics: Epics to skip (decision=EXCLUDE from scorecard).
        """
        self._configs = configs or {}
        self.excluded_epics: set[str] = excluded_epics or set()

    @classmethod
    def from_optimal_thresholds(
        cls,
        path: Path | None = None,
    ) -> "StrategyManager":
        """
        Create StrategyManager with per-asset confidence thresholds
        from the optimal_thresholds.json generated by batch_oos_scorecard.py.

        If the file doesn't exist, falls back to default config.
        """
        from src.backtest.scorecard import load_optimal_thresholds

        thresholds_path = path or _DEFAULT_THRESHOLDS_PATH
        data = load_optimal_thresholds(thresholds_path)

        if data is None:
            logger.info("No optimal_thresholds.json found, using default configs")
            return cls()

        per_asset = data.get("per_asset", {})
        default_conf = data.get("default_confidence", 0.40)
        configs: dict[str, StrategyConfig] = {}
        excluded: set[str] = set()

        for epic, info in per_asset.items():
            decision = info.get("decision", "KEEP")
            if decision == "EXCLUDE":
                excluded.add(epic)
                continue
            min_conf = info.get("min_confidence", default_conf)
            configs[epic] = StrategyConfig(epic=epic, min_confidence=min_conf)

        logger.info(
            f"Loaded optimal thresholds for {len(configs)} assets "
            f"({len(excluded)} excluded) from {thresholds_path}"
        )
        return cls(configs=configs, excluded_epics=excluded)

    def _get_config(self, epic: str) -> StrategyConfig:
        """Get or create config for an asset."""
        if epic not in self._configs:
            self._configs[epic] = StrategyConfig(epic=epic)
        return self._configs[epic]

    def process_prediction(
        self,
        prediction: PredictionResult,
        epic: str,
        market_data: dict,
    ) -> TradingSignal:
        """
        Process an ML prediction into a trading signal.

        Args:
            prediction: ML model prediction
            epic: Asset epic code
            market_data: Dict with keys:
                - current_price (float, required)
                - atr (float, required)
                - rsi (float, optional)
                - regime (str, optional)

        Returns:
            TradingSignal with direction and suggested levels
        """
        current_price = market_data.get("current_price")
        atr = market_data.get("atr")
        if current_price is None or atr is None:
            raise ValueError(
                "market_data must contain 'current_price' and 'atr' keys"
            )
        if not (isinstance(current_price, (int, float)) and current_price > 0):
            raise ValueError(f"Invalid current_price: {current_price}")
        if not (isinstance(atr, (int, float)) and atr > 0):
            raise ValueError(f"Invalid ATR: {atr}")
        rsi = market_data.get("rsi")
        regime = market_data.get("regime")
        adx = market_data.get("adx")

        # Get base config and adapt for regime
        base_config = self._get_config(epic)
        adapted_config = RegimeAdapter.adapt_params(regime, base_config)

        # Generate signal
        signal = SignalGenerator.generate_signal(
            prediction=prediction,
            epic=epic,
            current_price=current_price,
            atr=atr,
            rsi=rsi,
            regime=regime,
            config=adapted_config,
            adx=adx,
        )

        # Set strategy name (SignalGenerator doesn't set it)
        if signal.strategy_name is None:
            signal.strategy_name = "ml_strategy"

        logger.info(
            f"Strategy [{epic}]: {signal.direction.value} "
            f"conf={signal.confidence:.2f} regime={regime}"
        )

        return signal

    def get_allocation(self, regime: str | None = None) -> dict[str, float]:
        """
        Get portfolio allocation weights.

        Args:
            regime: Market regime for adjustment

        Returns:
            Dict of epic -> allocation weight
        """
        return PortfolioAllocator.get_allocation(regime)
