"""
Strategy manager orchestrator.
Coordinates regime adaptation, signal generation, and portfolio allocation.
"""

from datetime import UTC, datetime
from pathlib import Path

from loguru import logger

from src.models.schemas import PredictionResult
from src.strategy.portfolio_allocator import PortfolioAllocator
from src.strategy.regime_adapter import RegimeAdapter
from src.strategy.schemas import SignalDirection, StrategyConfig, TradingSignal
from src.strategy.signal_generator import SignalGenerator
from src.utils.config import get_settings

# Default location for per-asset thresholds produced by batch_oos_scorecard.py
_DEFAULT_THRESHOLDS_PATH = (
    Path(__file__).resolve().parent.parent.parent / "data" / "config" / "optimal_thresholds.json"
)


class StrategyManager:
    """
    Orchestrates the strategy pipeline:
    prediction -> regime adaptation -> signal generation.
    """

    def __init__(
        self,
        configs: dict[str, StrategyConfig] | None = None,
        excluded_epics: set[str] | None = None,
        scalp_mode: bool = False,
        orb_fvg_epics: set[str] | None = None,
        ml_primary_enabled: bool = False,
    ):
        """
        Initialize strategy manager.

        Args:
            configs: Per-asset strategy configs. Uses defaults if None.
            excluded_epics: Epics to skip (decision=EXCLUDE from scorecard).
            scalp_mode: If True, use ScalpScoreStrategy as primary signal source.
            orb_fvg_epics: Epics to use ORB+FVG strategy (default: {"US500"}).
            ml_primary_enabled: If True, ML decides direction, ScalpScore confirms quality.
        """
        self._configs = configs or {}
        self.excluded_epics: set[str] = excluded_epics or set()
        self.scalp_mode = scalp_mode
        self._ml_primary_enabled = ml_primary_enabled
        self._scalp_strategy = None
        self._orb_fvg_strategy = None
        self.orb_fvg_epics: set[str] = orb_fvg_epics if orb_fvg_epics is not None else {"US500"}
        if scalp_mode or ml_primary_enabled:
            from src.strategy.scalp_score_strategy import ScalpScoreStrategy

            self._scalp_strategy = ScalpScoreStrategy()
        if self.orb_fvg_epics:
            from src.strategy.orb_fvg_strategy import OrbFvgStrategy

            self._orb_fvg_strategy = OrbFvgStrategy()

    @classmethod
    def from_optimal_thresholds(
        cls,
        path: Path | None = None,
    ) -> "StrategyManager":
        """
        Create StrategyManager with per-asset confidence thresholds
        from the optimal_thresholds.json generated by batch_oos_scorecard.py.

        If the file doesn't exist, falls back to default config.
        """
        from src.backtest.scorecard import load_optimal_thresholds

        thresholds_path = path or _DEFAULT_THRESHOLDS_PATH
        data = load_optimal_thresholds(thresholds_path)

        if data is None:
            logger.info("No optimal_thresholds.json found, using default configs")
            return cls()

        per_asset = data.get("per_asset", {})
        default_conf = data.get("default_confidence", 0.40)
        configs: dict[str, StrategyConfig] = {}
        excluded: set[str] = set()

        for epic, info in per_asset.items():
            decision = info.get("decision", "KEEP")
            if decision == "EXCLUDE":
                excluded.add(epic)
                continue
            min_conf = info.get("min_confidence", default_conf)
            configs[epic] = StrategyConfig(epic=epic, min_confidence=min_conf)

        logger.info(
            f"Loaded optimal thresholds for {len(configs)} assets "
            f"({len(excluded)} excluded) from {thresholds_path}"
        )
        return cls(configs=configs, excluded_epics=excluded)

    def _get_config(self, epic: str) -> StrategyConfig:
        """Get or create config for an asset."""
        if epic not in self._configs:
            self._configs[epic] = StrategyConfig(epic=epic)
        return self._configs[epic]

    def process_prediction(
        self,
        prediction: PredictionResult,
        epic: str,
        market_data: dict,
    ) -> TradingSignal:
        """
        Process an ML prediction into a trading signal.

        Args:
            prediction: ML model prediction
            epic: Asset epic code
            market_data: Dict with keys:
                - current_price (float, required)
                - atr (float, required)
                - rsi (float, optional)
                - regime (str, optional)

        Returns:
            TradingSignal with direction and suggested levels
        """
        current_price = market_data.get("current_price")
        atr = market_data.get("atr")
        if current_price is None or atr is None:
            raise ValueError("market_data must contain 'current_price' and 'atr' keys")
        if not (isinstance(current_price, (int, float)) and current_price > 0):
            raise ValueError(f"Invalid current_price: {current_price}")
        if not (isinstance(atr, (int, float)) and atr > 0):
            raise ValueError(f"Invalid ATR: {atr}")

        # Mean Reversion Primary: MR rules decide direction, XGBoost scores quality
        _settings = get_settings()
        if _settings.mr_primary_enabled:
            from src.strategy.mean_reversion_strategy import MeanReversionStrategy

            mr = MeanReversionStrategy()
            mr_signal = mr.generate_signal(market_data, epic=epic)

            # Build a full audit trail compatible with the signal-audit drawer
            # (votes / gates / market_snapshot). Even though MR uses a
            # different evidence model than ScalpScore, we map its inputs
            # onto the same audit shape so the drawer renders the
            # decisional path uniformly across strategies.
            adx_val = float(market_data.get("adx", 0))
            rsi_val = float(market_data.get("rsi", 50))
            vwap_val = float(market_data.get("vwap", 0))
            vwap_z_val = float(market_data.get("vwap_z_score", 0))
            bb_pctb_val = float(market_data.get("bb_pctb", 0.5))
            atr_val = float(market_data.get("atr", 0))
            sil_composite = float(market_data.get("sil_composite_score", 0))

            # Sentiment vote: SIL composite ranges roughly 0–1. >0.6 bullish,
            # <0.35 bearish, otherwise neutral. Mirrors the thresholds used
            # by ScalpScoreStrategy._vote_sentiment so the audit reads the
            # same across strategies.
            if sil_composite <= 0.0:
                sentiment_vote = 0
            elif sil_composite > 0.6:
                sentiment_vote = 1
            elif sil_composite < 0.35:
                sentiment_vote = -1
            else:
                sentiment_vote = 0

            # Z-score "vote" — direction = sign of -z (price above mean → SELL)
            z_vote = 0
            if mr_signal.z_score >= _settings.mr_z_entry:
                z_vote = -1  # mean-reversion: high z → SELL
            elif mr_signal.z_score <= -_settings.mr_z_entry:
                z_vote = 1  # mean-reversion: low z → BUY

            # RSI vote in MR sense: OB → SELL bias, OS → BUY bias
            if rsi_val > 70:
                rsi_vote = -1
            elif rsi_val < 30:
                rsi_vote = 1
            else:
                rsi_vote = 0

            # VWAP-z secondary directional vote
            if vwap_z_val >= _settings.mr_z_entry:
                vwap_vote = -1
            elif vwap_z_val <= -_settings.mr_z_entry:
                vwap_vote = 1
            else:
                vwap_vote = 0

            mr_votes = {
                "z_score": {"value": z_vote, "z": round(mr_signal.z_score, 3)},
                "rsi": {"value": rsi_vote, "rsi": round(rsi_val, 1)},
                "vwap_z": {"value": vwap_vote, "z": round(vwap_z_val, 3)},
                "bb_pctb": {
                    "value": -1 if bb_pctb_val > 1.0 else 1 if bb_pctb_val < 0.0 else 0,
                    "pctb": round(bb_pctb_val, 3),
                },
                "sentiment": {
                    "value": sentiment_vote,
                    "composite": round(sil_composite, 3),
                    "available": sil_composite > 0,
                },
            }

            mr_market_snapshot = {
                "price": round(current_price, 5),
                "atr": round(atr_val, 5),
                "rsi": round(rsi_val, 1),
                "adx": round(adx_val, 1),
                "vwap": round(vwap_val, 5) if vwap_val else 0,
                "vwap_z": round(vwap_z_val, 3),
                "bb_pctb": round(bb_pctb_val, 3),
                "sentiment_composite": round(sil_composite, 3),
            }

            def _mr_gates(
                *, trending_pass: bool, z_pass: bool, quality_pass: bool, ml_agrees: bool | None
            ) -> dict:
                return {
                    "trending_filter": {
                        "passed": trending_pass,
                        "adx": round(adx_val, 1),
                        "adx_max": _settings.mr_adx_max,
                        "reason": (
                            None
                            if trending_pass
                            else f"ADX {adx_val:.1f} > {_settings.mr_adx_max:.0f} (trending)"
                        ),
                    },
                    "z_threshold": {
                        "passed": z_pass,
                        "z": round(mr_signal.z_score, 3),
                        "z_entry": _settings.mr_z_entry,
                        "reason": (
                            None
                            if z_pass
                            else f"|z| {abs(mr_signal.z_score):.2f} < entry {_settings.mr_z_entry:.2f}"
                        ),
                    },
                    "quality_gate": {
                        "passed": quality_pass,
                        "min_quality": _settings.mr_min_quality,
                        "reason": (
                            None
                            if quality_pass
                            else f"Quality below {_settings.mr_min_quality:.2f}"
                        ),
                    },
                    "ml_agreement": {
                        "passed": ml_agrees if ml_agrees is not None else True,
                        "ml_direction": prediction.signal_name if prediction else None,
                        "mr_direction": mr_signal.direction,
                    },
                }

            if mr_signal.direction == "HOLD":
                # Trending vs no-extreme — mr_signal.reason carries the cause.
                trending_hit = adx_val > _settings.mr_adx_max
                return TradingSignal(
                    epic=epic,
                    direction=SignalDirection.HOLD,
                    confidence=0.0,
                    signal_class=1,
                    regime=market_data.get("regime"),
                    timestamp=datetime.now(UTC),
                    technical_confirmation=False,
                    entry_price=market_data.get("current_price", 0),
                    suggested_stop=None,
                    suggested_tp=None,
                    strategy_name="mean_reversion",
                    metadata={
                        "votes": mr_votes,
                        "gates": _mr_gates(
                            trending_pass=not trending_hit,
                            z_pass=False,
                            quality_pass=True,  # quality gate not reached at this point
                            ml_agrees=None,
                        ),
                        "market_snapshot": mr_market_snapshot,
                        "rejection_reason": mr_signal.reason,
                        "mr_reason": mr_signal.reason,
                        "mr_z": mr_signal.z_score,
                    },
                )

            # XGBoost quality score: use prediction confidence as setup quality
            quality = prediction.confidence if prediction else 0.0

            # --- DUAL DIRECTION LOGGING (added 2026-04-14) ---
            ml_direction = prediction.signal_name if prediction else "NONE"
            mr_direction = mr_signal.direction
            agrees = ml_direction == mr_direction
            logger.info(
                f"[{epic}] DIRECTION AUDIT: "
                f"MR={mr_direction} ML={ml_direction} agree={agrees} "
                f"ml_conf={quality:.3f} mr_z={mr_signal.z_score:.2f} "
                f"adx={market_data.get('adx', 0):.1f}"
            )

            # Direction from MR rules, not from XGBoost
            direction = (
                SignalDirection.BUY if mr_signal.direction == "BUY" else SignalDirection.SELL
            )

            # Sentiment confidence adjustment (was inert under MR-Primary mode):
            # apply a small, capped boost when the SIL composite agrees with
            # the MR direction, and a small penalty when it disagrees. The
            # signal-audit drawer surfaces this so the user sees sentiment
            # contributing to the decision instead of being silently dropped.
            sentiment_adj = 0.0
            if sil_composite > 0:
                if (direction == SignalDirection.BUY and sentiment_vote > 0) or (
                    direction == SignalDirection.SELL and sentiment_vote < 0
                ):
                    sentiment_adj = +0.10
                elif (direction == SignalDirection.BUY and sentiment_vote < 0) or (
                    direction == SignalDirection.SELL and sentiment_vote > 0
                ):
                    sentiment_adj = -0.10
            quality_pre_sentiment = quality
            quality = max(0.0, min(1.0, quality + sentiment_adj))

            # Apply quality gate
            if quality < _settings.mr_min_quality:
                return TradingSignal(
                    epic=epic,
                    direction=SignalDirection.HOLD,
                    confidence=quality,
                    signal_class=1,
                    regime=market_data.get("regime"),
                    timestamp=datetime.now(UTC),
                    technical_confirmation=False,
                    entry_price=market_data.get("current_price", 0),
                    suggested_stop=mr_signal.stop_level,
                    suggested_tp=mr_signal.tp_level,
                    strategy_name="mean_reversion",
                    metadata={
                        "votes": mr_votes,
                        "gates": _mr_gates(
                            trending_pass=True,
                            z_pass=True,
                            quality_pass=False,
                            ml_agrees=agrees,
                        ),
                        "market_snapshot": mr_market_snapshot,
                        "ml": {
                            "signal_class": prediction.signal_class if prediction else 1,
                            "signal_name": ml_direction,
                            "confidence": round(quality_pre_sentiment, 4),
                            "probabilities": prediction.probabilities if prediction else {},
                            "agreement": "agree" if agrees else "disagree",
                            "confidence_before": round(quality_pre_sentiment, 4),
                            "confidence_after": round(quality, 4),
                        },
                        "rejection_reason": (
                            f"Quality {quality:.2f} < {_settings.mr_min_quality:.2f}"
                        ),
                        "mr_reason": (f"Quality {quality:.2f} < {_settings.mr_min_quality:.2f}"),
                        "mr_z": mr_signal.z_score,
                        "mr_quality": quality,
                        "ml_direction": ml_direction,
                        "ml_agrees": agrees,
                        "sentiment_adj": sentiment_adj,
                    },
                )

            logger.info(
                f"MR-Primary [{epic}]: {mr_signal.direction} "
                f"(z={mr_signal.z_score:.2f}, quality={quality:.2f}, "
                f"sentiment_adj={sentiment_adj:+.2f})"
            )

            return TradingSignal(
                epic=epic,
                direction=direction,
                confidence=quality,
                signal_class=2 if direction == SignalDirection.BUY else 0,
                regime=market_data.get("regime"),
                timestamp=datetime.now(UTC),
                technical_confirmation=True,
                entry_price=market_data.get("current_price", 0),
                suggested_stop=mr_signal.stop_level,
                suggested_tp=mr_signal.tp_level,
                strategy_name="mean_reversion",
                metadata={
                    "votes": mr_votes,
                    "gates": _mr_gates(
                        trending_pass=True,
                        z_pass=True,
                        quality_pass=True,
                        ml_agrees=agrees,
                    ),
                    "market_snapshot": mr_market_snapshot,
                    "ml": {
                        "signal_class": prediction.signal_class if prediction else 1,
                        "signal_name": ml_direction,
                        "confidence": round(quality_pre_sentiment, 4),
                        "probabilities": prediction.probabilities if prediction else {},
                        "agreement": "agree" if agrees else "disagree",
                        "confidence_before": round(quality_pre_sentiment, 4),
                        "confidence_after": round(quality, 4),
                    },
                    "mr_z": mr_signal.z_score,
                    "mr_quality": quality,
                    "mr_direction": mr_signal.direction,
                    "mr_reason": mr_signal.reason,
                    "ml_direction": ml_direction,
                    "ml_agrees": agrees,
                    "adx": market_data.get("adx", 0),
                    "sentiment_adj": sentiment_adj,
                },
            )

        # Route to ORB+FVG for configured epics during NYSE hours
        if (
            self._orb_fvg_strategy is not None
            and epic in self.orb_fvg_epics
            and market_data.get("m1_bars") is not None
        ):
            return self._process_orb_fvg(epic, market_data)

        # ML-Primary mode: ML decides direction, ScalpScore confirms quality
        if self._ml_primary_enabled and self._scalp_strategy is not None:
            return self._process_ml_primary(prediction, epic, market_data)

        if self.scalp_mode and self._scalp_strategy is not None:
            return self._process_scalp(prediction, epic, market_data)

        rsi = market_data.get("rsi")
        regime = market_data.get("regime")
        adx = market_data.get("adx")

        # Get base config and adapt for regime
        base_config = self._get_config(epic)
        adapted_config = RegimeAdapter.adapt_params(regime, base_config)

        # Generate signal
        signal = SignalGenerator.generate_signal(
            prediction=prediction,
            epic=epic,
            current_price=current_price,
            atr=atr,
            rsi=rsi,
            regime=regime,
            config=adapted_config,
            adx=adx,
        )

        # Set strategy name (SignalGenerator doesn't set it)
        if signal.strategy_name is None:
            signal.strategy_name = "ml_strategy"

        logger.info(
            f"Strategy [{epic}]: {signal.direction.value} "
            f"conf={signal.confidence:.2f} regime={regime}"
        )

        return signal

    def _process_orb_fvg(
        self,
        epic: str,
        market_data: dict,
    ) -> TradingSignal:
        """Route to ORB+FVG strategy using M1 bars from market_data."""

        m1_bars = market_data["m1_bars"]
        current_price = float(market_data["current_price"])
        atr = float(market_data["atr"])

        config = StrategyConfig(
            epic=epic,
            stop_multiplier=1.0,
            risk_reward_ratio=2.0,
        )

        current_bar = {"close": current_price, "atr_14": atr}

        signal = self._orb_fvg_strategy.generate_signal(epic, current_bar, m1_bars, config)

        if signal.direction.value != "HOLD":
            logger.info(
                f"ORB+FVG [{epic}]: {signal.direction.value} " f"conf={signal.confidence:.2f}"
            )

        return signal

    def _process_scalp(
        self,
        prediction: PredictionResult,
        epic: str,
        market_data: dict,
    ) -> TradingSignal:
        """Scalp mode: technical score first, ML as boost layer."""
        # Use module-level `datetime` import (line 6) so test fixtures that
        # patch `src.strategy.strategy_manager.datetime` actually apply
        # here. The inline `from datetime import datetime` previously
        # shadowed the patch with the real stdlib class.
        import polars as pl

        from src.models.schemas import SignalClass
        from src.strategy.schemas import SignalDirection

        current_price = float(market_data["current_price"])
        atr = float(market_data["atr"])
        utc_hour = datetime.now(UTC).hour

        config = StrategyConfig(
            epic=epic,
            stop_multiplier=1.0,
            risk_reward_ratio=2.0,
            min_confidence=0.40,
        )

        # Build current_bar from market_data
        current_bar = {
            "close": current_price,
            "atr_14": atr,
            "rsi_14": market_data.get("rsi", 50),
            "adx_14": market_data.get("adx", 0),
            "ema_9": market_data.get("ema_9", 0),
            "ema_21": market_data.get("ema_21", 0),
            "macd_histogram": market_data.get("macd_histogram", 0),
            "macd": market_data.get("macd", 0),
            "macd_signal": market_data.get("macd_signal", 0),
            "volume": market_data.get("volume", 0),
            "volume_sma_20": market_data.get("volume_sma_20", 0),
            "bb_upper": market_data.get("bb_upper", 0),
            "bb_lower": market_data.get("bb_lower", 0),
            "bb_middle": market_data.get("bb_middle", 0),
            "keltner_upper": market_data.get("keltner_upper", 0),
            "keltner_lower": market_data.get("keltner_lower", 0),
            "vwap": market_data.get("vwap", 0),
            "utc_hour": utc_hour,
            "htf_bias": market_data.get("htf_bias"),
        }

        recent_bars = market_data.get("recent_bars", pl.DataFrame({"close": [current_price]}))

        # Step 1: Technical score signal
        signal = self._scalp_strategy.generate_signal(epic, current_bar, recent_bars, config)

        if signal.direction == SignalDirection.HOLD:
            logger.info(f"Scalp [{epic}]: HOLD (score too low)")
            return signal

        # Step 2: ML boost layer
        ml_direction = {
            SignalClass.BUY: SignalDirection.BUY,
            SignalClass.SELL: SignalDirection.SELL,
            SignalClass.HOLD: SignalDirection.HOLD,
        }.get(prediction.signal_class, SignalDirection.HOLD)

        pre_ml_confidence = signal.confidence

        if ml_direction == signal.direction and prediction.confidence > 0.40:
            # ML agrees -> full confidence (no change)
            agreement = "agree"
            logger.info(
                f"Scalp [{epic}]: {signal.direction.value} "
                f"(score->signal, ML agrees conf={prediction.confidence:.2f})"
            )
        elif ml_direction == SignalDirection.HOLD or prediction.confidence <= 0.40:
            # ML neutral -> mild reduction (×0.75), not halving.
            # Halving a 3/7 (0.43) signal to 0.21 kills it below the 0.25 floor.
            # Neutral ML means "no opinion", not "bad signal".
            agreement = "neutral"
            signal = signal.model_copy(update={"confidence": signal.confidence * 0.75})
            logger.info(
                f"Scalp [{epic}]: {signal.direction.value} "
                f"(score->signal, ML neutral -> 0.75x conf={signal.confidence:.2f})"
            )
        else:
            # ML disagrees — halve confidence but never veto
            # GURU: technical confluence is the decision maker, ML only adjusts sizing
            agreement = "disagree"
            signal = signal.model_copy(update={"confidence": signal.confidence * 0.5})
            logger.info(
                f"Scalp [{epic}]: {signal.direction.value} "
                f"(ML disagrees {ml_direction.value} conf={prediction.confidence:.2f} -> half conf={signal.confidence:.2f})"
            )

        # Add ML audit data to signal metadata
        ml_audit = {
            "signal_class": prediction.signal_class,
            "signal_name": prediction.signal_name,
            "confidence": round(prediction.confidence, 4),
            "probabilities": prediction.probabilities,
            "agreement": agreement,
            "confidence_before": round(pre_ml_confidence, 4),
            "confidence_after": round(signal.confidence, 4),
        }
        updated_metadata = {**signal.metadata, "ml": ml_audit}
        signal = signal.model_copy(
            update={"strategy_name": "scalp_score", "metadata": updated_metadata}
        )
        return signal

    def _process_ml_primary(
        self,
        prediction: PredictionResult,
        epic: str,
        market_data: dict,
    ) -> TradingSignal:
        """ML-Primary mode: ML decides direction, ScalpScore confirms quality."""
        # Use module-level `datetime` import (line 6) so test fixtures that
        # patch `src.strategy.strategy_manager.datetime` actually apply
        # here. The inline `from datetime import datetime` previously
        # shadowed the patch with the real stdlib class.
        import polars as pl

        from src.models.schemas import SignalClass
        from src.strategy.schemas import SignalDirection
        from src.utils.config import get_settings

        settings = get_settings()
        current_price = float(market_data["current_price"])
        atr = float(market_data["atr"])
        utc_hour = datetime.now(UTC).hour

        # Step 1: Map ML prediction to direction
        ml_direction = {
            SignalClass.BUY: SignalDirection.BUY,
            SignalClass.SELL: SignalDirection.SELL,
            SignalClass.HOLD: SignalDirection.HOLD,
        }.get(prediction.signal_class, SignalDirection.HOLD)

        # Step 2: HOLD gate
        if ml_direction == SignalDirection.HOLD:
            logger.info(f"ML-Primary [{epic}]: HOLD (ML predicts HOLD)")
            return self._make_hold(epic, current_price)

        # Step 3: Min confidence gate
        if prediction.confidence < settings.ml_primary_min_confidence:
            logger.info(
                f"ML-Primary [{epic}]: HOLD (ML conf={prediction.confidence:.2f} "
                f"< min={settings.ml_primary_min_confidence})"
            )
            return self._make_hold(epic, current_price)

        # Step 4: Build current_bar (same as _process_scalp)
        current_bar = {
            "close": current_price,
            "atr_14": atr,
            "rsi_14": market_data.get("rsi", 50),
            "adx_14": market_data.get("adx", 0),
            "ema_9": market_data.get("ema_9", 0),
            "ema_21": market_data.get("ema_21", 0),
            "macd_histogram": market_data.get("macd_histogram", 0),
            "macd": market_data.get("macd", 0),
            "macd_signal": market_data.get("macd_signal", 0),
            "volume": market_data.get("volume", 0),
            "volume_sma_20": market_data.get("volume_sma_20", 0),
            "bb_upper": market_data.get("bb_upper", 0),
            "bb_lower": market_data.get("bb_lower", 0),
            "bb_middle": market_data.get("bb_middle", 0),
            "keltner_upper": market_data.get("keltner_upper", 0),
            "keltner_lower": market_data.get("keltner_lower", 0),
            "vwap": market_data.get("vwap", 0),
            "utc_hour": utc_hour,
            "htf_bias": market_data.get("htf_bias"),
            "sil_composite_score": market_data.get("sil_composite_score", 0.0),
        }
        recent_bars = market_data.get("recent_bars", pl.DataFrame({"close": [current_price]}))

        # Step 5: Evaluate technical quality
        quality = self._scalp_strategy.evaluate_technical_quality(
            ml_direction,
            epic,
            current_bar,
            recent_bars,
        )

        # Step 6: Hard gates (session, dead market)
        if quality["session_blocked"]:
            logger.debug(f"ML-Primary [{epic}]: HOLD (session blocked)")
            return self._make_hold(epic, current_price)
        if quality["dead_market_blocked"]:
            logger.debug(f"ML-Primary [{epic}]: HOLD (dead market)")
            return self._make_hold(epic, current_price)

        # Step 7: Composite confidence
        tech_quality = quality["quality_score"]
        tech_mult = min(1.0, 0.40 + tech_quality * 0.85)
        composite = prediction.confidence * tech_mult

        if not quality["vwap_aligned"]:
            composite *= settings.ml_primary_vwap_penalty

        if quality["htf_aligned"] is False:
            composite *= settings.ml_primary_htf_penalty
        elif quality["htf_aligned"] is True:
            composite = min(1.0, composite * 1.05)

        # Step 8: Technical floor
        if tech_quality < settings.ml_primary_min_technical_quality:
            logger.info(
                f"ML-Primary [{epic}]: HOLD (tech quality {tech_quality:.2f} "
                f"< min={settings.ml_primary_min_technical_quality})"
            )
            return self._make_hold(epic, current_price)

        # Step 9: SL/TP
        config = StrategyConfig(
            epic=epic,
            stop_multiplier=1.0,
            risk_reward_ratio=2.0,
        )
        sl_mult = config.stop_multiplier
        rr = config.risk_reward_ratio
        if ml_direction == SignalDirection.BUY:
            stop = current_price - atr * sl_mult
            tp = current_price + atr * sl_mult * rr
            signal_class = SignalClass.BUY
        else:
            stop = current_price + atr * sl_mult
            tp = current_price - atr * sl_mult * rr
            signal_class = SignalClass.SELL

        # Log
        votes = quality["votes_detail"]
        votes_str = (
            f"EMA={votes.get('ema', 0):+d} RSI={votes.get('rsi', 0):+d} "
            f"MACD={votes.get('macd', 0):+d} BB={votes.get('bb', 0):+d} "
            f"VOL={votes.get('vol', 0):+d} ADX={votes.get('adx', 0):+d} "
            f"SENT={votes.get('sentiment', 0):+d}"
        )
        vwap_tag = " VWAP=opposed" if not quality["vwap_aligned"] else ""
        htf_tag = " HTF=opposed" if quality["htf_aligned"] is False else ""
        logger.info(
            f"ML-Primary [{epic}]: {ml_direction.value} "
            f"(ml_conf={prediction.confidence:.2f}, "
            f"tech={quality['agreeing_votes']}/7, "
            f"composite={composite:.2f}) "
            f"[{votes_str}]{vwap_tag}{htf_tag}"
        )

        # Step 10: Build signal
        audit_metadata = {
            "ml": {
                "signal_class": prediction.signal_class,
                "signal_name": prediction.signal_name,
                "confidence": round(prediction.confidence, 4),
                "probabilities": prediction.probabilities,
            },
            "technical_quality": {
                "agreeing_votes": quality["agreeing_votes"],
                "opposing_votes": quality["opposing_votes"],
                "quality_score": quality["quality_score"],
                "tech_multiplier": round(tech_mult, 4),
                "vwap_aligned": quality["vwap_aligned"],
                "htf_aligned": quality["htf_aligned"],
                "votes_detail": quality["votes_detail"],
            },
            "composite_confidence": round(composite, 4),
            "penalties": {
                "vwap": not quality["vwap_aligned"],
                "htf": quality["htf_aligned"] is False,
            },
        }

        return TradingSignal(
            epic=epic,
            direction=ml_direction,
            confidence=composite,
            signal_class=signal_class,
            entry_price=current_price,
            suggested_stop=stop,
            suggested_tp=tp,
            technical_confirmation=quality["agreeing_votes"] >= 3,
            strategy_name="ml_primary",
            metadata=audit_metadata,
        )

    @staticmethod
    def _make_hold(epic: str, price: float) -> TradingSignal:
        """Create a HOLD signal."""
        from src.models.schemas import SignalClass
        from src.strategy.schemas import SignalDirection

        return TradingSignal(
            epic=epic,
            direction=SignalDirection.HOLD,
            confidence=0.0,
            signal_class=SignalClass.HOLD,
            entry_price=price,
            technical_confirmation=False,
        )

    def get_allocation(self, regime: str | None = None) -> dict[str, float]:
        """
        Get portfolio allocation weights.

        Args:
            regime: Market regime for adjustment

        Returns:
            Dict of epic -> allocation weight
        """
        return PortfolioAllocator.get_allocation(regime)
