"""
Signal repository for ML predictions and trading signals.
"""

from datetime import UTC, datetime

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from src.database.models import Signal
from src.database.repository import BaseRepository


class SignalRepository(BaseRepository[Signal]):
    """Repository for Signal model with ML-specific queries."""

    def __init__(self, session: AsyncSession):
        super().__init__(Signal, session)

    async def get_pending_signals(self, epic: str | None = None) -> list[Signal]:
        """
        Get pending signals (not yet executed).

        Args:
            epic: Optional epic filter

        Returns:
            List of pending signals
        """
        query = select(Signal).where(Signal.status == "PENDING")
        if epic:
            query = query.where(Signal.epic == epic)
        query = query.order_by(Signal.generated_at.desc())

        result = await self.session.execute(query)
        return list(result.scalars().all())

    async def get_by_confidence_threshold(
        self, epic: str, min_confidence: float, status: str = "PENDING"
    ) -> list[Signal]:
        """
        Get signals above confidence threshold.

        Args:
            epic: Asset epic code
            min_confidence: Minimum confidence (0.0 to 1.0)
            status: Signal status filter

        Returns:
            List of high-confidence signals
        """
        result = await self.session.execute(
            select(Signal)
            .where(Signal.epic == epic)
            .where(Signal.confidence >= min_confidence)
            .where(Signal.status == status)
            .order_by(Signal.confidence.desc())
        )
        return list(result.scalars().all())

    async def get_by_model(self, model_id: int, limit: int = 100) -> list[Signal]:
        """
        Get signals generated by a specific model.

        Args:
            model_id: Model ID
            limit: Maximum signals to return

        Returns:
            List of signals
        """
        result = await self.session.execute(
            select(Signal)
            .where(Signal.model_id == model_id)
            .order_by(Signal.generated_at.desc())
            .limit(limit)
        )
        return list(result.scalars().all())

    async def get_recent_signals(
        self, epic: str, hours: int = 24, direction: str | None = None
    ) -> list[Signal]:
        """
        Get recent signals for an asset.

        Args:
            epic: Asset epic code
            hours: Hours to look back
            direction: Optional direction filter (BUY, SELL, HOLD)

        Returns:
            List of recent signals
        """
        since = datetime.now(UTC).replace(microsecond=0)
        since = since.replace(hour=since.hour - hours)

        query = select(Signal).where(Signal.epic == epic).where(Signal.generated_at >= since)
        if direction:
            query = query.where(Signal.direction == direction)
        query = query.order_by(Signal.generated_at.desc())

        result = await self.session.execute(query)
        return list(result.scalars().all())

    async def mark_as_executed(self, signal_id: int, position_id: int) -> Signal | None:
        """
        Mark signal as executed and link to position.

        Args:
            signal_id: Signal ID
            position_id: Position ID that was created from this signal

        Returns:
            Updated signal or None if not found
        """
        signal = await self.get_by_id(signal_id)
        if not signal:
            return None

        signal.status = "EXECUTED"
        signal.position_id = position_id

        await self.session.flush()
        await self.session.refresh(signal)
        return signal

    async def mark_as_rejected(self, signal_id: int) -> Signal | None:
        """
        Mark signal as rejected (didn't pass risk checks).

        Args:
            signal_id: Signal ID

        Returns:
            Updated signal or None if not found
        """
        signal = await self.get_by_id(signal_id)
        if not signal:
            return None

        signal.status = "REJECTED"

        await self.session.flush()
        await self.session.refresh(signal)
        return signal

    async def create_from_audit(
        self,
        epic: str,
        direction: str,
        confidence: float,
        entry_price: float | None,
        stop_loss: float | None,
        take_profit: float | None,
        status: str,
        features: dict,
    ) -> int | None:
        """Create a signal record with full audit trail JSONB."""
        from decimal import Decimal

        now = datetime.now(UTC).replace(tzinfo=None)

        signal = Signal(
            epic=epic,
            timeframe="15min",
            direction=direction,
            confidence=Decimal(str(round(confidence, 4))),
            predicted_price=Decimal(str(round(entry_price, 4))) if entry_price else None,
            stop_loss_price=Decimal(str(round(stop_loss, 4))) if stop_loss else None,
            take_profit_price=Decimal(str(round(take_profit, 4))) if take_profit else None,
            model_version="scalp_score_v1",
            features=features,
            status=status,
            generated_at=now,
        )
        self.session.add(signal)
        await self.session.flush()
        await self.session.refresh(signal)
        return signal.id

    async def get_by_position_deal_id(self, deal_id: str) -> Signal | None:
        """Find the signal linked to a position by deal_id.

        First tries exact match via Signal→Position FK join.
        If not found, looks up the position's epic and returns the most recent
        EXECUTED signal for that epic (handles broker deal_id rotation).
        """
        from src.database.models import Position

        # Try exact FK match first
        result = await self.session.execute(
            select(Signal)
            .join(Position, Signal.position_id == Position.id)
            .where(Position.deal_id == deal_id)
            .order_by(Signal.generated_at.desc())
            .limit(1)
        )
        signal = result.scalars().first()
        if signal:
            return signal

        # Fallback: find position epic, then most recent EXECUTED signal for it
        pos_result = await self.session.execute(
            select(Position.epic).where(Position.deal_id == deal_id).limit(1)
        )
        epic = pos_result.scalar_one_or_none()
        if not epic:
            return None

        result = await self.session.execute(
            select(Signal)
            .where(Signal.epic == epic, Signal.status == "EXECUTED")
            .order_by(Signal.generated_at.desc())
            .limit(1)
        )
        return result.scalars().first()

    async def get_latest_by_epic(self, epic: str) -> Signal | None:
        """Get the most recent EXECUTED signal for an epic (with full features)."""
        result = await self.session.execute(
            select(Signal)
            .where(Signal.epic == epic, Signal.status == "EXECUTED")
            .order_by(Signal.generated_at.desc())
            .limit(1)
        )
        return result.scalars().first()

    async def get_history_by_epic(self, epic: str, limit: int = 10, offset: int = 0) -> list[dict]:
        """Get lightweight signal history for an epic (no JSONB features)."""
        from sqlalchemy import case

        from src.database.models import Position

        query = (
            select(
                Signal.id,
                Signal.direction,
                Signal.confidence,
                Signal.status,
                Signal.generated_at,
                Signal.features["rejection_reason"].as_string().label("rejection_reason"),
                Position.profit_loss.label("position_pnl"),
                case(
                    (Position.status == "OPEN", "OPEN"),
                    (Position.status == "CLOSED", "CLOSED"),
                    else_=None,
                ).label("position_status"),
            )
            .outerjoin(Position, Signal.position_id == Position.id)
            .where(Signal.epic == epic)
            .where(Signal.status.in_(["EXECUTED", "REJECTED"]))
            .order_by(Signal.generated_at.desc())
            .offset(offset)
            .limit(limit)
        )
        result = await self.session.execute(query)
        rows = result.all()

        return [
            {
                "id": row.id,
                "epic": epic,
                "direction": row.direction,
                "confidence": float(row.confidence),
                "status": row.status,
                "generated_at": row.generated_at.isoformat() if row.generated_at else None,
                "rejection_reason": row.rejection_reason,
                "position_pnl": float(row.position_pnl) if row.position_pnl else None,
                "position_status": row.position_status,
            }
            for row in rows
        ]

    async def count_by_epic(self, epic: str) -> int:
        """Count total signals for an epic."""
        from sqlalchemy import func

        result = await self.session.execute(
            select(func.count(Signal.id))
            .where(Signal.epic == epic)
            .where(Signal.status.in_(["EXECUTED", "REJECTED"]))
        )
        return result.scalar() or 0

    async def expire_old_signals(self) -> int:
        """Expire pending signals past their expiration date."""
        now = datetime.now(UTC)
        result = await self.session.execute(
            select(Signal).where(Signal.status == "PENDING").where(Signal.expires_at <= now)
        )
        signals = list(result.scalars().all())

        for signal in signals:
            signal.status = "EXPIRED"

        await self.session.flush()
        return len(signals)
