"""
Signal repository for ML predictions and trading signals.
"""

from datetime import datetime

from sqlalchemy import select
from sqlalchemy.ext.asyncio import AsyncSession

from src.database.models import Signal
from src.database.repository import BaseRepository


class SignalRepository(BaseRepository[Signal]):
    """Repository for Signal model with ML-specific queries."""

    def __init__(self, session: AsyncSession):
        super().__init__(Signal, session)

    async def get_pending_signals(self, epic: str | None = None) -> list[Signal]:
        """
        Get pending signals (not yet executed).

        Args:
            epic: Optional epic filter

        Returns:
            List of pending signals
        """
        query = select(Signal).where(Signal.status == "PENDING")
        if epic:
            query = query.where(Signal.epic == epic)
        query = query.order_by(Signal.generated_at.desc())

        result = await self.session.execute(query)
        return list(result.scalars().all())

    async def get_by_confidence_threshold(
        self, epic: str, min_confidence: float, status: str = "PENDING"
    ) -> list[Signal]:
        """
        Get signals above confidence threshold.

        Args:
            epic: Asset epic code
            min_confidence: Minimum confidence (0.0 to 1.0)
            status: Signal status filter

        Returns:
            List of high-confidence signals
        """
        result = await self.session.execute(
            select(Signal)
            .where(Signal.epic == epic)
            .where(Signal.confidence >= min_confidence)
            .where(Signal.status == status)
            .order_by(Signal.confidence.desc())
        )
        return list(result.scalars().all())

    async def get_by_model(self, model_id: int, limit: int = 100) -> list[Signal]:
        """
        Get signals generated by a specific model.

        Args:
            model_id: Model ID
            limit: Maximum signals to return

        Returns:
            List of signals
        """
        result = await self.session.execute(
            select(Signal)
            .where(Signal.model_id == model_id)
            .order_by(Signal.generated_at.desc())
            .limit(limit)
        )
        return list(result.scalars().all())

    async def get_recent_signals(
        self, epic: str, hours: int = 24, direction: str | None = None
    ) -> list[Signal]:
        """
        Get recent signals for an asset.

        Args:
            epic: Asset epic code
            hours: Hours to look back
            direction: Optional direction filter (BUY, SELL, HOLD)

        Returns:
            List of recent signals
        """
        since = datetime.utcnow().replace(microsecond=0)
        since = since.replace(hour=since.hour - hours)

        query = (
            select(Signal)
            .where(Signal.epic == epic)
            .where(Signal.generated_at >= since)
        )
        if direction:
            query = query.where(Signal.direction == direction)
        query = query.order_by(Signal.generated_at.desc())

        result = await self.session.execute(query)
        return list(result.scalars().all())

    async def mark_as_executed(self, signal_id: int, position_id: int) -> Signal | None:
        """
        Mark signal as executed and link to position.

        Args:
            signal_id: Signal ID
            position_id: Position ID that was created from this signal

        Returns:
            Updated signal or None if not found
        """
        signal = await self.get_by_id(signal_id)
        if not signal:
            return None

        signal.status = "EXECUTED"
        signal.position_id = position_id

        await self.session.flush()
        await self.session.refresh(signal)
        return signal

    async def mark_as_rejected(self, signal_id: int) -> Signal | None:
        """
        Mark signal as rejected (didn't pass risk checks).

        Args:
            signal_id: Signal ID

        Returns:
            Updated signal or None if not found
        """
        signal = await self.get_by_id(signal_id)
        if not signal:
            return None

        signal.status = "REJECTED"

        await self.session.flush()
        await self.session.refresh(signal)
        return signal

    async def expire_old_signals(self) -> int:
        """
        Expire pending signals past their expiration date.

        Returns:
            Number of signals expired
        """
        now = datetime.utcnow()
        result = await self.session.execute(
            select(Signal)
            .where(Signal.status == "PENDING")
            .where(Signal.expires_at <= now)
        )
        signals = list(result.scalars().all())

        for signal in signals:
            signal.status = "EXPIRED"

        await self.session.flush()
        return len(signals)
