-- ═══════════════════════════════════════════════════════════════════════════
-- Trade Logging Schema - PostgreSQL Tables
-- ═══════════════════════════════════════════════════════════════════════════
-- Purpose: Store structured logs for signals, executions, and risk decisions
-- Version: 1.0.0
-- Created: 2026-02-14
-- ═══════════════════════════════════════════════════════════════════════════

-- ───────────────────────────────────────────────────────────────────────────
-- 1. Signal Log Table
-- ───────────────────────────────────────────────────────────────────────────
-- Stores all trading signals generated by strategies

CREATE TABLE IF NOT EXISTS signal_log (
    id SERIAL PRIMARY KEY,
    timestamp TIMESTAMP NOT NULL DEFAULT NOW(),
    epic VARCHAR(20) NOT NULL,
    direction VARCHAR(10) NOT NULL CHECK (direction IN ('LONG', 'SHORT', 'HOLD')),
    confidence DECIMAL(5, 4) NOT NULL CHECK (confidence >= 0.0 AND confidence <= 1.0),
    strategy VARCHAR(50) NOT NULL,

    -- Feature snapshot (JSON)
    features JSONB DEFAULT '{}',

    -- ML model details
    model_version VARCHAR(50),
    model_proba JSONB,  -- {"LONG": 0.7, "SHORT": 0.2, "HOLD": 0.1}

    -- Execution outcome
    execution_status VARCHAR(20) CHECK (execution_status IN (
        'executed', 'rejected', 'exec_failed', 'hold', 'market_closed'
    )),
    rejection_reason TEXT,

    -- Indexes
    created_at TIMESTAMP DEFAULT NOW()
);

-- Indexes for fast queries
CREATE INDEX IF NOT EXISTS idx_signal_log_timestamp ON signal_log (timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_signal_log_epic ON signal_log (epic);
CREATE INDEX IF NOT EXISTS idx_signal_log_strategy ON signal_log (strategy);
CREATE INDEX IF NOT EXISTS idx_signal_log_direction ON signal_log (direction);
CREATE INDEX IF NOT EXISTS idx_signal_log_execution_status ON signal_log (execution_status);

-- Composite index for common query patterns
CREATE INDEX IF NOT EXISTS idx_signal_log_epic_timestamp ON signal_log (epic, timestamp DESC);


-- ───────────────────────────────────────────────────────────────────────────
-- 2. Execution Log Table
-- ───────────────────────────────────────────────────────────────────────────
-- Stores all trade executions (entry and exit)

CREATE TABLE IF NOT EXISTS execution_log (
    id SERIAL PRIMARY KEY,
    timestamp TIMESTAMP NOT NULL DEFAULT NOW(),
    deal_id VARCHAR(50) UNIQUE,  -- Broker deal ID
    epic VARCHAR(20) NOT NULL,
    direction VARCHAR(10) NOT NULL CHECK (direction IN ('BUY', 'SELL')),
    size DECIMAL(12, 4) NOT NULL,
    entry_price DECIMAL(12, 2) NOT NULL,
    stop_loss DECIMAL(12, 2),
    take_profit DECIMAL(12, 2),

    -- Execution details
    status VARCHAR(20) NOT NULL CHECK (status IN (
        'executed', 'rejected', 'exec_failed', 'hold', 'market_closed'
    )),
    error_message TEXT,

    -- Position sizing details
    kelly_fraction DECIMAL(5, 4),
    risk_pct DECIMAL(5, 2),
    equity_at_entry DECIMAL(12, 2),

    -- Exit details (NULL until position closed)
    exit_price DECIMAL(12, 2),
    exit_timestamp TIMESTAMP,
    realized_pnl DECIMAL(12, 2),

    -- Metadata
    created_at TIMESTAMP DEFAULT NOW()
);

-- Indexes for fast queries
CREATE INDEX IF NOT EXISTS idx_execution_log_timestamp ON execution_log (timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_execution_log_epic ON execution_log (epic);
CREATE INDEX IF NOT EXISTS idx_execution_log_deal_id ON execution_log (deal_id);
CREATE INDEX IF NOT EXISTS idx_execution_log_status ON execution_log (status);
CREATE INDEX IF NOT EXISTS idx_execution_log_exit_timestamp ON execution_log (exit_timestamp);

-- Composite index for open positions (NULL exit_timestamp)
CREATE INDEX IF NOT EXISTS idx_execution_log_open_positions
    ON execution_log (epic, exit_timestamp) WHERE exit_timestamp IS NULL;


-- ───────────────────────────────────────────────────────────────────────────
-- 3. Risk Event Log Table
-- ───────────────────────────────────────────────────────────────────────────
-- Stores all risk management decisions and circuit breaker events

CREATE TABLE IF NOT EXISTS risk_event_log (
    id SERIAL PRIMARY KEY,
    timestamp TIMESTAMP NOT NULL DEFAULT NOW(),
    source VARCHAR(40) NOT NULL DEFAULT 'unknown',  -- paper_trading / demo_trading / live_trading / api_test
    event_type VARCHAR(30) NOT NULL CHECK (event_type IN (
        'circuit_breaker', 'position_limit', 'drawdown_limit',
        'equity_filter', 'consecutive_loss', 'daily_loss'
    )),
    epic VARCHAR(20),  -- NULL for global events
    description TEXT NOT NULL,

    -- Risk metrics snapshot
    current_equity DECIMAL(12, 2),
    peak_equity DECIMAL(12, 2),
    current_drawdown_pct DECIMAL(5, 2),
    daily_pnl DECIMAL(12, 2),
    open_positions INTEGER,
    consecutive_losses INTEGER,

    -- Action taken
    action VARCHAR(100) NOT NULL,

    -- Metadata
    created_at TIMESTAMP DEFAULT NOW()
);

-- Indexes for fast queries
CREATE INDEX IF NOT EXISTS idx_risk_event_log_timestamp ON risk_event_log (timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_risk_event_log_event_type ON risk_event_log (event_type);
CREATE INDEX IF NOT EXISTS idx_risk_event_log_epic ON risk_event_log (epic);
CREATE INDEX IF NOT EXISTS idx_risk_event_log_source ON risk_event_log (source);

-- Composite index for circuit breaker analysis
CREATE INDEX IF NOT EXISTS idx_risk_event_log_type_timestamp
    ON risk_event_log (event_type, timestamp DESC);


-- ═══════════════════════════════════════════════════════════════════════════
-- Views for Common Queries
-- ═══════════════════════════════════════════════════════════════════════════

-- ───────────────────────────────────────────────────────────────────────────
-- View: Recent Signals (last 7 days)
-- ───────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE VIEW recent_signals AS
SELECT
    timestamp,
    epic,
    direction,
    confidence,
    strategy,
    execution_status,
    rejection_reason
FROM signal_log
WHERE timestamp >= NOW() - INTERVAL '7 days'
ORDER BY timestamp DESC;


-- ───────────────────────────────────────────────────────────────────────────
-- View: Open Positions (from execution_log)
-- ───────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE VIEW open_positions AS
SELECT
    deal_id,
    epic,
    direction,
    size,
    entry_price,
    stop_loss,
    take_profit,
    timestamp AS opened_at,
    equity_at_entry
FROM execution_log
WHERE exit_timestamp IS NULL
  AND status = 'executed'
ORDER BY timestamp DESC;


-- ───────────────────────────────────────────────────────────────────────────
-- View: Closed Trades (with P&L)
-- ───────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE VIEW closed_trades AS
SELECT
    deal_id,
    epic,
    direction,
    size,
    entry_price,
    exit_price,
    realized_pnl,
    timestamp AS opened_at,
    exit_timestamp AS closed_at,
    EXTRACT(EPOCH FROM (exit_timestamp - timestamp)) / 3600 AS duration_hours
FROM execution_log
WHERE exit_timestamp IS NOT NULL
  AND status = 'executed'
ORDER BY exit_timestamp DESC;


-- ───────────────────────────────────────────────────────────────────────────
-- View: Risk Events (last 30 days)
-- ───────────────────────────────────────────────────────────────────────────
CREATE OR REPLACE VIEW recent_risk_events AS
SELECT
    timestamp,
    event_type,
    epic,
    description,
    current_drawdown_pct,
    daily_pnl,
    action
FROM risk_event_log
WHERE timestamp >= NOW() - INTERVAL '30 days'
ORDER BY timestamp DESC;


-- ═══════════════════════════════════════════════════════════════════════════
-- Sample Queries (for documentation)
-- ═══════════════════════════════════════════════════════════════════════════

-- Get signal win rate by strategy (last 30 days)
-- SELECT
--     strategy,
--     COUNT(*) AS total_signals,
--     SUM(CASE WHEN execution_status = 'executed' THEN 1 ELSE 0 END) AS executed,
--     SUM(CASE WHEN execution_status = 'rejected' THEN 1 ELSE 0 END) AS rejected,
--     ROUND(100.0 * SUM(CASE WHEN execution_status = 'executed' THEN 1 ELSE 0 END) / COUNT(*), 2) AS execution_rate_pct
-- FROM signal_log
-- WHERE timestamp >= NOW() - INTERVAL '30 days'
-- GROUP BY strategy
-- ORDER BY total_signals DESC;

-- Get P&L by asset
-- SELECT
--     epic,
--     COUNT(*) AS trades,
--     SUM(realized_pnl) AS total_pnl,
--     AVG(realized_pnl) AS avg_pnl,
--     SUM(CASE WHEN realized_pnl > 0 THEN 1 ELSE 0 END) AS wins,
--     ROUND(100.0 * SUM(CASE WHEN realized_pnl > 0 THEN 1 ELSE 0 END) / COUNT(*), 2) AS win_rate_pct
-- FROM execution_log
-- WHERE exit_timestamp IS NOT NULL
--   AND status = 'executed'
-- GROUP BY epic
-- ORDER BY total_pnl DESC;

-- Get circuit breaker frequency
-- SELECT
--     event_type,
--     COUNT(*) AS occurrences,
--     MAX(timestamp) AS last_occurrence
-- FROM risk_event_log
-- WHERE timestamp >= NOW() - INTERVAL '30 days'
-- GROUP BY event_type
-- ORDER BY occurrences DESC;
